// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/google/wire"
	"github.com/jw803/webook/internal/interface/event/article"
	"github.com/jw803/webook/internal/interface/web/user"
	"github.com/jw803/webook/internal/pkg/ginx/jwt_handler"
	"github.com/jw803/webook/internal/repository"
	"github.com/jw803/webook/internal/repository/cache"
	"github.com/jw803/webook/internal/repository/dao"
	"github.com/jw803/webook/internal/service"
	"github.com/jw803/webook/ioc"
	"github.com/jw803/webook/pkg/samarax"
)

// Injectors from wire.go:

func InitUserhandler(userDAO dao.UserDAO) *user.UserHandler {
	cmdable := ioc.InitRedis()
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewCachedUserRepository(userDAO, userCache)
	logger := ioc.InitLogger()
	userService := service.NewUserService(userRepository, logger)
	codeCache := cache.NewRedisCodeCache(cmdable, logger)
	codeRepository := repository.NewCachedCodeRepository(codeCache)
	smsService := ioc.InitSmsMemoryService(cmdable)
	codeService := service.NewSMSCodeService(codeRepository, smsService)
	jwtHandler := jwtx.NewRedisHandler(cmdable)
	userHandler := user.NewUserHandler(userService, codeService, jwtHandler, logger)
	return userHandler
}

// wire.go:

var thirdProvider = wire.NewSet(ioc.InitDB, ioc.InitRedis, ioc.InitSaramaClient, ioc.InitLogger, ioc.NewUuidFn)

var eventProvider = wire.NewSet(ioc.NewConsumers, article.NewInteractiveReadEventConsumer, samarax.NewSamaraxBaseHandler)
