// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	article3 "github.com/jw803/webook/internal/interface/web/article"
	"github.com/jw803/webook/internal/interface/web/user"
	"github.com/jw803/webook/internal/pkg/ginx/jwt_handler"
	"github.com/jw803/webook/internal/repository"
	article2 "github.com/jw803/webook/internal/repository/article"
	"github.com/jw803/webook/internal/repository/cache"
	"github.com/jw803/webook/internal/repository/dao"
	"github.com/jw803/webook/internal/repository/dao/article"
	"github.com/jw803/webook/internal/service"
	"github.com/jw803/webook/ioc"
)

// Injectors from wire.go:

func InitApp() *App {
	cmdable := ioc.InitRedis()
	handler := jwtx.NewRedisHandler(cmdable)
	logger := ioc.InitLogger()
	v := ioc.GinMiddlewares(handler, logger)
	db := ioc.InitDB()
	userDAO := dao.NewGORMUserDAO(db)
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewCachedUserRepository(userDAO, userCache)
	userService := service.NewUserService(userRepository, logger)
	codeCache := cache.NewRedisCodeCache(cmdable, logger)
	codeRepository := repository.NewCachedCodeRepository(codeCache)
	smsService := ioc.InitSmsMemoryService(cmdable)
	codeService := service.NewSMSCodeService(codeRepository, smsService)
	userHandler := user.NewUserHandler(userService, codeService, handler, logger)
	articleDAO := article.NewGORMArticleDAO(db)
	articleCache := cache.NewRedisArticleCache(cmdable)
	articleRepository := article2.NewArticleRepository(articleDAO, articleCache)
	articleService := service.NewArticleService(articleRepository)
	articleHandler := article3.NewArticleHandler(articleService, logger)
	v2 := ioc.InitWebServer(v, userHandler, articleHandler)
	v3 := ioc.NewConsumers()
	app := &App{
		webServer: v2,
		consumers: v3,
	}
	return app
}

// wire.go:

var eventProvider = wire.NewSet(ioc.NewConsumers)

var webProvider = wire.NewSet(jwtx.NewRedisHandler, user.NewUserHandler, article3.NewArticleHandler, ioc.GinMiddlewares, ioc.InitWebServer)
